import { PermissionEnum } from './permission'

export const PagePermission = {
  ADMIN_ARTICLE_LIST: [PermissionEnum.ADMIN_ARTICLE_LIST],
  ADMIN_ARTICLE_CREATE: [PermissionEnum.ADMIN_ARTICLE_CREATE],
  ADMIN_ARTICLE_UPDATE: [PermissionEnum.ADMIN_ARTICLE_UPDATE, PermissionEnum.ADMIN_ARTICLE_SHOW],
  ADMIN_ARTICLE_DETAIL: [PermissionEnum.ADMIN_ARTICLE_SHOW],
  ADMIN_ARTICLE_LANGUAGE_CREATE: [PermissionEnum.ADMIN_ARTICLE_LANGUAGE_CREATE],
  ADMIN_ARTICLE_LANGUAGE_UPDATE: [
    PermissionEnum.ADMIN_ARTICLE_LANGUAGE_SHOW,
    PermissionEnum.ADMIN_ARTICLE_LANGUAGE_UPDATE,
  ],

  ADMIN_BANNER_LIST: [PermissionEnum.ADMIN_BANNER_LIST],
  ADMIN_BANNER_CREATE: [PermissionEnum.ADMIN_BANNER_CREATE],
  ADMIN_BANNER_UPDATE: [PermissionEnum.ADMIN_BANNER_UPDATE],

  ADMIN_CATEGORY_LIST: [PermissionEnum.ADMIN_CATEGORY_LIST],
  ADMIN_CATEGORY_CREATE: [PermissionEnum.ADMIN_CATEGORY_CREATE],
  ADMIN_CATEGORY_DETAIL: [PermissionEnum.ADMIN_CATEGORY_SHOW],

  ADMIN_MAIN_PAGE_VIDEO_LIST: [PermissionEnum.ADMIN_MAIN_PAGE_VIDEO_LIST],
  ADMIN_MAIN_PAGE_VIDEO_CREATE: [PermissionEnum.ADMIN_MAIN_PAGE_VIDEO_CREATE],
  ADMIN_MAIN_PAGE_VIDEO_DETAIL: [PermissionEnum.ADMIN_MAIN_PAGE_VIDEO_SHOW],
  ADMIN_MAIN_PAGE_VIDEO_UPDATE: [PermissionEnum.ADMIN_MAIN_PAGE_VIDEO_UPDATE],

  ADMIN_OUR_TEAM_PAGE_TEAM_LIST: [PermissionEnum.ADMIN_OUR_TEAM_PAGE_TEAM_FETCH],

  ADMIN_PROJECT_LIST: [PermissionEnum.ADMIN_PROJECT_LIST],
  ADMIN_PROJECT_CREATE: [PermissionEnum.ADMIN_PROJECT_CREATE],
  ADMIN_PROJECT_DETAIL: [PermissionEnum.ADMIN_PROJECT_SHOW],
  ADMIN_PROJECT_UPDATE: [PermissionEnum.ADMIN_PROJECT_UPDATE],
  ADMIN_PROJECT_IMAGE_DETAIL: [PermissionEnum.ADMIN_PROJECT_IMAGE_SHOW],
  ADMIN_PROJECT_REVIEW_DETAIL: [PermissionEnum.ADMIN_PROJECT_REVIEW_SHOW],

  ADMIN_PROJECT_LABEL_LIST: [PermissionEnum.ADMIN_PROJECT_LABEL_LIST],
  ADMIN_PROJECT_LABEL_CREATE: [PermissionEnum.ADMIN_PROJECT_LABEL_CREATE],
  ADMIN_PROJECT_LABEL_DETAIL: [PermissionEnum.ADMIN_PROJECT_LABEL_SHOW],

  ADMIN_PROJECT_GROUP_LIST: [PermissionEnum.ADMIN_PROJECT_GROUP_LIST],
  ADMIN_PROJECT_GROUP_CREATE: [PermissionEnum.ADMIN_PROJECT_GROUP_CREATE],
  ADMIN_PROJECT_GROUP_DETAIL: [PermissionEnum.ADMIN_PROJECT_GROUP_SHOW],

  ADMIN_PROJECT_SERVICE_LIST: [PermissionEnum.ADMIN_PROJECT_SERVICE_LIST],
  ADMIN_PROJECT_SERVICE_CREATE: [PermissionEnum.ADMIN_PROJECT_SERVICE_CREATE],
  ADMIN_PROJECT_SERVICE_DETAIL: [PermissionEnum.ADMIN_PROJECT_SERVICE_SHOW],

  ADMIN_PROMOTION_LIST: [PermissionEnum.ADMIN_PROMOTION_LIST],
  ADMIN_PROMOTION_CREATE: [PermissionEnum.ADMIN_PROMOTION_CREATE],
  ADMIN_PROMOTION_UPDATE: [PermissionEnum.ADMIN_PROMOTION_SHOW, PermissionEnum.ADMIN_PROMOTION_UPDATE],
  ADMIN_PROMOTION_DETAIL: [PermissionEnum.ADMIN_PROMOTION_SHOW],
  ADMIN_PROMOTION_LANGUAGE_CREATE: [PermissionEnum.ADMIN_PROMOTION_LANGUAGE_CREATE],
  ADMIN_PROMOTION_LANGUAGE_UPDATE: [
    PermissionEnum.ADMIN_PROMOTION_LANGUAGE_SHOW,
    PermissionEnum.ADMIN_PROMOTION_LANGUAGE_UPDATE,
  ],

  ADMIN_MAIN_PAGE_PROJECT_GROUP_LIST: [PermissionEnum.ADMIN_MAIN_PAGE_PROJECT_GROUP_FETCH],

  ADMIN_MAIN_PAGE_TEAM_LIST: [PermissionEnum.ADMIN_MAIN_PAGE_TEAM_FETCH],

  ADMIN_TEAM_LIST: [PermissionEnum.ADMIN_TEAM_LIST],
  ADMIN_TEAM_CREATE: [PermissionEnum.ADMIN_TEAM_CREATE],
  ADMIN_TEAM_UPDATE: [PermissionEnum.ADMIN_TEAM_UPDATE],
  ADMIN_TEAM_DETAIL: [PermissionEnum.ADMIN_TEAM_SHOW],
}
