const PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_WIDTH = 3
const PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_HEIGHT = 1
const PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO =
  PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_WIDTH / PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_HEIGHT
const PROMOTION_IMAGE_THUMBNAIL_MAX_FILE_SIZE = 1 * 1024 * 1024 // 1MB
const PROMOTION_IMAGE_THUMBNAIL_CROP_WIDTH = 600
const PROMOTION_IMAGE_THUMBNAIL_MIN_RESOLUTION_WIDTH = 600
const PROMOTION_IMAGE_THUMBNAIL_MIN_RESOLUTION_HEIGHT = 600 / PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO

export {
  PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_WIDTH,
  PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO_HEIGHT,
  PROMOTION_IMAGE_THUMBNAIL_ASPECT_RATIO,
  PROMOTION_IMAGE_THUMBNAIL_MAX_FILE_SIZE,
  PROMOTION_IMAGE_THUMBNAIL_CROP_WIDTH,
  PROMOTION_IMAGE_THUMBNAIL_MIN_RESOLUTION_WIDTH,
  PROMOTION_IMAGE_THUMBNAIL_MIN_RESOLUTION_HEIGHT,
}
