const DOCTOR_IMAGE_ASPECT_RATIO = 5 / 6
const DOCTOR_IMAGE_WIDTH = 420
const DOCTOR_THUMBNAIL_IMAGE_WIDTH = 350

export { DOCTOR_IMAGE_ASPECT_RATIO, DOCTOR_IMAGE_WIDTH, DOCTOR_THUMBNAIL_IMAGE_WIDTH }
