const MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_WIDTH = 16
const MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_HEIGHT = 9
const MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO =
  MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_WIDTH / MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_HEIGHT
const MAIN_PAGE_VIDEO_THUMNAIL_MAX_FILE_SIZE = 1 * 1024 * 1024 // 1MB
const MAIN_PAGE_VIDEO_CROP_WIDTH = 1200
const MAIN_PAGE_VIDEO_MIN_RESOLUTION_WIDTH = 1200
const MAIN_PAGE_VIDEO_MIN_RESOLUTION_HEIGHT = 1200 / MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO

export {
  MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_WIDTH,
  MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO_HEIGHT,
  MAIN_PAGE_VIDEO_THUMBNAIL_ASPECT_RATIO,
  MAIN_PAGE_VIDEO_THUMNAIL_MAX_FILE_SIZE,
  MAIN_PAGE_VIDEO_CROP_WIDTH,
  MAIN_PAGE_VIDEO_MIN_RESOLUTION_WIDTH,
  MAIN_PAGE_VIDEO_MIN_RESOLUTION_HEIGHT,
}
